#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba16) uniform readonly image2D inputImage;
layout (set = 1, binding = 1, rgba16) uniform image2D resultImage;

void main()
{
	//vec4 res = vec4(0.5f);

	ivec2 currentPixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(resultImage);

	vec2 texCoord = vec2(currentPixel) / size;

	vec4 res = imageLoad(inputImage, currentPixel);

	imageStore(resultImage, currentPixel, res);
}